* declaration for the long text
DATA: BEGIN OF ICDTXT_ZCM_CDO_02 OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZCM_CDO_02.
DATA: UPD_ICDTXT_ZCM_CDO_02 TYPE C.

* table with the NEW content of: ZCM_TABLO_1
DATA: BEGIN OF XZCM_TABLO_1 OCCURS 20.
        INCLUDE STRUCTURE ZZCM_TABLO_1.
DATA: END OF XZCM_TABLO_1.

* table with the OLD content of: ZCM_TABLO_1
DATA: BEGIN OF YZCM_TABLO_1 OCCURS 20.
        INCLUDE STRUCTURE ZZCM_TABLO_1.
DATA: END OF YZCM_TABLO_1.

DATA: UPD_ZCM_TABLO_1 TYPE C.

